Remove throughput chart annotations
The annotations in the chart cause an issue where the chart cannot
render because it's too large. This has been outlined in [1].

The error is:
ValueError: Image size of 15443364x1476 pixels is too large. It must
be less than 2^16 in each direction.

[1] https://github.com/DeloitteDigitalUK/jira-agile-metrics/issues/30